import type { Metadata } from "next";

// These styles apply to every route in the application
import "./globals.css";
import React from "react";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-center" />
        <Header />
        {children}
      </body>
    </html>
  );
}
